rvm: '2.6.0'

script:
  - mkdir -p spec && bundle exec rspec spec

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq postgresql-server-dev-9.3

services:
  - postgresql

before_script:
  - psql -c 'create database chitter_test;' -U postgres
  - psql -c 'create table peeps(id SERIAL PRIMARY KEY, text VARCHAR(60), created_at TIMESTAMP NOT NULL DEFAULT NOW(), user_id INT);'
  - psql -c 'create table users (id SERIAL PRIMARY KEY, name VARCHAR(20), username VARCHAR(20), email VARCHAR(30), password VARCHAR(20));
  - psql -c 'alter table peeps add foreign key (user_id) references users(id);'
